import type { Course } from '@/types';

// The master bookable course list — powers the Reservations.tsx dropdown.
// Ids match content/coursesDetail.ts's ids 1:1 (both are keyed the same way
// Strapi's `courses` collection will be: by the course's real id/slug), so
// the "Book This Course" link on a course detail page always resolves to
// the same entry in this list, whether the data comes from local fallback
// content or from Strapi.
export const COURSES: Course[] = [
  {
    id: 'open-water',
    name: 'SDI Open Water Scuba Diver',
    category: 'Beginner',
    agency: 'SDI',
    overview: 'Your gateway to underwater exploration. This comprehensive course teaches fundamental knowledge and practical skills needed to dive safely to 18 meters independently with a buddy. Perfect for beginners.',
    prerequisites: 'Minimum age 10, comfortable swimming ability, medical clearance.',
    duration: '3 - 4 Days',
    certificationAwarded: 'SDI Open Water Diver (Lifetime, Globally Recognized)',
    includedMaterials: ['SDI eLearning Access', 'Digital Logbook', 'Premium Gear Rental', 'Certification Fees'],
    price: { amount: 450, currency: 'USD' },
    schedule: 'Day 1: Theory review & confined water skills. Day 2-3: Ocean training dives. Day 4: Final certification dives.',
  },
  {
    id: 'advanced-open-water',
    name: 'SDI Advanced Open Water Diver',
    category: 'Advanced',
    agency: 'SDI',
    overview: 'Build confidence and expand your diving capabilities. This course provides hands-on experience in advanced diving techniques, allowing you to dive to 30 meters with proper training and certification.',
    prerequisites: 'SDI Open Water Diver certification or equivalent.',
    duration: '2 - 3 Days',
    certificationAwarded: 'SDI Advanced Open Water Diver',
    includedMaterials: ['eLearning materials', 'Specialty equipment', '4 Ocean training dives'],
    price: { amount: 390, currency: 'USD' },
    schedule: 'Day 1: Navigation and buoyancy training. Day 2-3: Specialty dives including deep and drift diving.',
  },
  {
    id: 'rescue-diver',
    name: 'SDI Rescue Diver',
    category: 'Rescue',
    agency: 'SDI',
    overview: 'Develop critical rescue skills and emergency management techniques. This challenging course prepares you to assist other divers and handle emergency situations with confidence and professionalism.',
    prerequisites: 'Advanced Diver certification, current CPR/First Aid.',
    duration: '3 Days',
    certificationAwarded: 'SDI Rescue Diver',
    includedMaterials: ['SDI Rescue eLearning', 'Oxygen Provider training', 'Scenario-based training'],
    price: { amount: 480, currency: 'USD' },
    schedule: 'Day 1: Rescue theory and self-rescue techniques. Day 2: Confined water rescue drills. Day 3: Ocean rescue scenarios.',
  },
  {
    id: 'nitrox',
    name: 'TDI Enriched Air Nitrox Diver',
    category: 'Advanced',
    agency: 'TDI',
    overview: 'Learn to safely dive with Enriched Air Nitrox to extend your no-decompression limits, reduce surface intervals, and experience less post-dive fatigue. Our state-of-the-art Nitrox station supports this training.',
    prerequisites: 'Open Water Diver certification.',
    duration: '1 Day',
    certificationAwarded: 'TDI Nitrox Diver',
    includedMaterials: ['TDI Nitrox eLearning', 'Gas analysis workshop', '2 Nitrox cylinder fills'],
    price: { amount: 180, currency: 'USD' },
    schedule: 'Morning: Physics & physiology lecture, gas analyzer practice. Afternoon: Optional 2 dives using Nitrox.',
  },
  {
    id: 'wreck-diving',
    name: 'TDI Wreck Diving Specialty',
    category: 'Advanced',
    agency: 'TDI',
    overview: 'Explore the fascinating world of wreck diving. Learn specialized techniques for safe penetration, navigation, and artifact identification in underwater wreck environments.',
    prerequisites: 'Advanced Diver, 25 logged dives.',
    duration: '2 Days',
    certificationAwarded: 'TDI Wreck Diving Specialty',
    includedMaterials: ['TDI Wreck manual', 'Specialty equipment', '3 wreck training dives'],
    price: { amount: 320, currency: 'USD' },
    schedule: 'Day 1: Wreck diving theory and confined water training. Day 2: Two guided wreck dives.',
  },
  {
    id: 'deep-diver',
    name: 'TDI Deep Diver Specialty',
    category: 'Advanced',
    agency: 'TDI',
    overview: 'Master the skills required for deep diving beyond recreational limits. Learn decompression theory, gas management, and safety procedures for dives to 40 meters.',
    prerequisites: 'Advanced Diver, 25 logged dives.',
    duration: '2 Days',
    certificationAwarded: 'TDI Deep Diver',
    includedMaterials: ['TDI Deep Diving manual', 'Decompression tables', '3 deep training dives'],
    price: { amount: 350, currency: 'USD' },
    schedule: 'Day 1: Deep diving theory and planning. Day 2: Two deep training dives with decompression stops.',
  },
  {
    id: 'extended-range',
    name: 'SDI/TDI Extended Range Diver Course',
    category: 'Technical',
    agency: 'TDI',
    overview: 'The gateway into technical diving. Train for planned decompression dives beyond recreational limits using advanced equipment, gas management, and decompression procedures.',
    prerequisites: 'Advanced Diver, Nitrox certification, 25 logged dives.',
    duration: '4 - 5 Days',
    certificationAwarded: 'SDI/TDI Extended Range Diver',
    includedMaterials: ['TDI Extended Range manual', 'Twinset/sidemount equipment', 'Decompression gas fills'],
    price: { amount: 650, currency: 'USD' },
    schedule: 'Day 1-2: Technical diving theory, gas planning, and confined water skills. Day 3-5: Planned decompression training dives to 45-65 metres.',
  },
];
