import type { Course } from '@/types';

// Content for the 7 dedicated course detail pages (client/src/pages/courses/*.tsx),
// keyed by slug (matches each page's route, e.g. `/courses/open-water`). Ids here
// match content/courses.ts 1:1 so a course's "Book This Course" link (which uses
// the fetched course's real `id`) always resolves to the same entry in the
// Reservations.tsx dropdown.
export const COURSE_DETAILS: Record<string, Course> = {
  'open-water': {
    id: 'open-water',
    name: 'Open Water Diver Course',
    overview: 'Start your underwater adventure with the world\'s most popular scuba certification program.',
    eyebrow: 'Core Certification',
    heroDescription: 'Start your underwater adventure with the world\'s most popular scuba certification program.',
    overviewSection: {
      eyebrow: 'Your First Step',
      title: 'Start Your Underwater Adventure',
      description: 'The Open Water Diver Course is the world\'s most popular scuba certification program, designed for beginners with little or no diving experience. Upon successful completion, you will earn an internationally recognized certification allowing you to dive independently with a buddy anywhere in the world.',
    },
    highlightCard: {
      title: 'Internationally Recognized',
      text: 'Your Open Water certification is recognized worldwide. Once certified, you can dive with a buddy at any dive center around the globe, opening up a lifetime of underwater exploration.',
      icon: 'BookOpen',
    },
    learningPointsSection: { eyebrow: 'Curriculum', heading: 'What You\'ll Learn' },
    learningPoints: [
      'Basic scuba diving principles',
      'Dive equipment setup and use',
      'Underwater communication skills',
      'Buoyancy control techniques',
      'Dive planning and safety procedures',
      'Marine conservation awareness',
    ],
    ctaHeading: 'Ready to Take the Plunge?',
    ctaDescription: 'Begin your scuba diving journey today. No prior experience needed.',
  },
  'advanced-open-water': {
    id: 'advanced-open-water',
    name: 'Advanced Open Water Diver Course',
    overview: 'Build your confidence, expand your diving skills, and explore new underwater adventures.',
    eyebrow: 'Advanced Certification',
    heroDescription: 'Build your confidence, expand your diving skills, and explore new underwater adventures.',
    overviewSection: {
      eyebrow: 'Level Up',
      title: 'Take Your Diving to the Next Level',
      description: 'The Advanced Open Water Diver Course is designed to build your confidence, expand your diving skills, and introduce you to new underwater adventures. Through a series of specialty dives, you\'ll gain valuable experience while exploring different aspects of scuba diving.',
    },
    highlightCard: {
      title: 'Five Adventure Dives',
      text: 'The course includes five adventure dives that let you explore different specialties. Two required dives build essential skills, while three elective dives let you pursue your interests.',
      icon: 'Compass',
    },
    learningPointsSection: { eyebrow: 'Curriculum', heading: 'What You\'ll Learn' },
    learningPoints: [
      'Advanced buoyancy control',
      'Underwater navigation techniques',
      'Deep diving procedures',
      'Improved dive planning and awareness',
      'Specialty diving skills based on your interests',
    ],
    courseStructureSection: { eyebrow: 'Course Structure', heading: 'Five Adventure Dives' },
    requiredDives: ['Deep Dive', 'Underwater Navigation Dive'],
    optionalDives: [
      'Night Diving',
      'Drift Diving',
      'Wreck Diving',
      'Peak Performance Buoyancy',
      'Fish Identification',
      'Search and Recovery',
      'Underwater Photography',
    ],
    courseStructureNote: 'Plus three additional adventure dives of your choice',
    ctaHeading: 'Ready to Advance Your Skills?',
    ctaDescription: 'Take the next step in your diving journey with five exciting adventure dives.',
  },
  'rescue-diver': {
    id: 'rescue-diver',
    name: 'SDI Rescue Diver Course',
    overview: 'One of the most valuable recreational diving certifications. Learn to prevent accidents, recognize stress, and manage diving emergencies.',
    eyebrow: 'Safety & Rescue',
    heroDescription: 'One of the most valuable recreational diving certifications. Learn to prevent accidents, recognize stress, and manage diving emergencies.',
    overviewSection: {
      eyebrow: 'Bridge to Professional',
      title: 'Become a Confident Rescue Diver',
      description: 'The SDI Rescue Diver course is one of the most valuable recreational diving certifications because it focuses on preventing accidents, recognizing stress, and managing diving emergencies. It is often considered the bridge between recreational diving and professional-level training.',
    },
    highlightCard: {
      title: 'Professional-Level Skills',
      text: 'This course is often considered the bridge between recreational diving and professional-level training. The skills you develop here will make you a safer, more confident diver and a valuable dive buddy.',
      icon: 'Shield',
    },
    prerequisitesSection: { eyebrow: 'Requirements', heading: 'Prerequisites' },
    prerequisitesList: [
      'Minimum age 15 years (with parental consent) or 18 years depending on local standards',
      'Current CPR, First Aid, and Oxygen Provider certification',
      'SDI Advanced Adventure Diver certification (or equivalent), or Open Water certification with the required logged dives',
    ],
    learningPointsSection: { eyebrow: 'Curriculum', heading: 'What You Will Learn' },
    learningPoints: [
      'Self-rescue techniques',
      'Recognizing diver stress and panic',
      'Assisting tired or distressed divers',
      'Surface and underwater rescue procedures',
      'Search and recovery techniques for missing divers',
      'Emergency management and accident scene control',
      'Oxygen administration and diver first aid',
      'Hyperbaric injury awareness and emergency response procedures',
    ],
    ctaHeading: 'Ready to Save Lives Underwater?',
    ctaDescription: 'Develop the skills to handle emergencies and become the diver everyone wants as a buddy.',
  },
  'deep-diver': {
    id: 'deep-diver',
    name: 'SDI Deep Diver Course',
    overview: 'Go beyond recreational Open Water limits and learn to safely dive to depths of 40 metres / 130 feet.',
    eyebrow: 'Specialty Certification',
    heroDescription: 'Go beyond recreational Open Water limits and learn to safely dive to depths of 40 metres / 130 feet.',
    overviewSection: {
      eyebrow: 'Go Deeper',
      title: 'Explore Greater Depths Safely',
      description: 'Take your diving beyond recreational Open Water limits and learn to safely plan and conduct dives to depths of 40 metres / 130 feet. The SDI Deep Diver specialty focuses on deep dive planning, gas management, narcosis awareness, and emergency procedures.',
    },
    highlightCard: {
      title: '40 Metres / 130 Feet',
      text: 'Learn the skills and knowledge needed to safely plan and execute dives at greater depths, including managing nitrogen narcosis and gas consumption at depth.',
      icon: 'ArrowDown',
      notes: ['Advanced gas management techniques', 'Narcosis recognition and response'],
    },
    learningPointsSection: { eyebrow: 'Curriculum', heading: 'What You\'ll Learn' },
    learningPoints: [
      'Deep dive physics and physiology',
      'Nitrogen narcosis recognition and management',
      'Gas consumption and air management',
      'Deep dive planning and dive computer use',
      'Emergency procedures for deep diving',
      'Equipment considerations for deeper dives',
    ],
    ctaHeading: 'Ready to Dive Deeper?',
    ctaDescription: 'Extend your depth capabilities with proper training and expert guidance.',
  },
  'wreck-diving': {
    id: 'wreck-diving',
    name: 'SDI Wreck Diver Specialty Course',
    overview: 'Learn to safely explore sunken ships, aircraft, and other submerged structures while protecting these unique underwater environments.',
    eyebrow: 'Specialty Certification',
    heroDescription: 'Learn to safely explore sunken ships, aircraft, and other submerged structures while protecting these unique underwater environments.',
    overviewSection: {
      eyebrow: 'Explore History',
      title: 'Discover Sunken Worlds',
      description: 'The SDI Wreck Diver Specialty Course teaches divers how to safely explore sunken ships, aircraft, and other submerged structures while minimizing risks and protecting these unique underwater environments. The course combines classroom/theory sessions with open water dives to develop the skills needed for safe wreck exploration.',
    },
    highlightCard: {
      title: 'Theory + Open Water',
      text: 'The course combines classroom and theory sessions with open water dives, giving you hands-on experience navigating real wreck sites under expert supervision.',
      icon: 'Anchor',
    },
    prerequisitesSection: { eyebrow: 'Requirements', heading: 'Prerequisites' },
    prerequisitesList: [
      'Minimum age: 18 years (or 10 years with parental consent, depending on local standards)',
      'Certified as an Open Water Scuba Diver or equivalent',
      'Good health and comfortable buoyancy skills',
    ],
    learningPointsSection: { eyebrow: 'Curriculum', heading: 'Course Overview' },
    learningPoints: [
      'Safe wreck exploration techniques and procedures',
      'Hazard identification and risk management around submerged structures',
      'Line-laying and navigation inside and around wrecks',
      'Buoyancy and finning techniques to minimize silt disturbance',
      'Environmental awareness and wreck preservation',
      'Emergency procedures specific to wreck diving',
    ],
    ctaHeading: 'Ready to Explore Wrecks?',
    ctaDescription: 'Discover the thrill of exploring sunken history with proper training and safety skills.',
  },
  nitrox: {
    id: 'nitrox',
    name: 'SDI Enriched Air Nitrox (EANx) Diver Course',
    overview: 'One of the most valuable specialty certifications for recreational divers. Learn to safely use Enriched Air Nitrox with oxygen concentrations up to 40%.',
    eyebrow: 'Specialty Certification',
    heroDescription: 'One of the most valuable specialty certifications for recreational divers. Learn to safely use Enriched Air Nitrox with oxygen concentrations up to 40%.',
    overviewSection: {
      eyebrow: 'Dive Smarter',
      title: 'Extend Your Bottom Time',
      description: 'The SDI Nitrox Course is one of the most valuable specialty certifications for recreational divers. It teaches you how to safely use Enriched Air Nitrox (EANx) with oxygen concentrations up to 40%, giving you longer bottom times, shorter surface intervals, and greater safety margins.',
    },
    highlightCard: {
      title: 'Up to 40% Oxygen',
      text: 'Learn to analyze gas mixes, set your dive computer for Nitrox, and understand oxygen exposure limits. A must-have certification for any serious recreational diver.',
      icon: 'Wind',
    },
    learningPointsSection: { eyebrow: 'Advantages', heading: 'Benefits of Diving Nitrox' },
    learningPoints: [
      'Longer no-decompression limits',
      'Reduced nitrogen absorption',
      'Shorter surface intervals',
      'Increased safety margin on repetitive dives',
      'Often less post-dive fatigue reported by divers',
    ],
    prerequisitesSection: { eyebrow: 'Requirements', heading: 'Course Prerequisites' },
    prerequisitesList: [
      'Minimum age: typically 15 years (may vary by dive center)',
      'Certified Open Water Diver or equivalent (or enrolled in an Open Water course with some SDI programs)',
    ],
    ctaHeading: 'Ready to Dive with Nitrox?',
    ctaDescription: 'Get certified and enjoy longer, safer dives with Enriched Air Nitrox.',
  },
  'extended-range': {
    id: 'extended-range',
    name: 'SDI/TDI Extended Range Diver Course',
    overview: 'The gateway into technical diving. Train for planned decompression dives beyond recreational limits.',
    eyebrow: 'Technical Diving',
    heroDescription: 'The gateway into technical diving. Train for planned decompression dives beyond recreational limits.',
    overviewSection: {
      eyebrow: 'Beyond Recreational',
      title: 'Enter the World of Technical Diving',
      description: 'The Extended Range (XR) Diver Course is the gateway into technical diving. It trains divers to safely conduct planned decompression dives beyond recreational limits using advanced equipment, gas management, and decompression procedures. Depending on the agency and configuration, divers are typically trained for decompression dives to depths of approximately 45-65 metres.',
    },
    highlightCard: {
      title: 'Depths of 45-65 Metres',
      text: 'This course prepares you for planned decompression dives using advanced equipment configurations including twinset or sidemount systems, with decompression gases up to 100% oxygen.',
      icon: 'Gauge',
    },
    learningPointsSection: { eyebrow: 'Curriculum', heading: 'What You\'ll Learn' },
    learningPoints: [
      'Advanced dive planning',
      'Decompression theory and procedures',
      'Gas management and gas switching',
      'Twinset or sidemount equipment configuration',
      'Emergency procedures and problem-solving',
      'Team diving techniques',
      'Oxygen and decompression gas use up to 100% O₂',
    ],
    ctaHeading: 'Ready to Go Beyond Recreational Limits?',
    ctaDescription: 'Take the leap into technical diving with expert instruction and advanced training.',
  },
};
