import type { DiveSafari } from '@/types';
import { diveSafaris as diveSafariImages } from './media';

// Dive Dream operates 40+ dive sites across Mauritius (4 featured here).
export const DIVE_SAFARIS: DiveSafari[] = [
  {
    id: 'coin-de-mire',
    name: 'Coin de Mire',
    tagline: 'Dive the Legendary Coin de Mire',
    description: 'Located off the northern coast of Mauritius, the iconic Coin de Mire (also known as Gunner\'s Quoin) is one of the island\'s most renowned diving destinations. Its dramatic underwater topography, clear waters, and rich marine biodiversity make it a must-visit site for divers of all experience levels.',
    location: 'Northern Mauritius',
    maxDepth: '40m (130ft)',
    certificationLevel: 'Advanced',
    type: ['Deep', 'Wall', 'Drift'],
    marineLife: ['Groupers', 'Snappers', 'Barracudas', 'Reef Sharks', 'Large Pelagic Species'],
    highlights: [
      'Spectacular underwater cliffs and drop-offs',
      'Excellent visibility, often exceeding 20 metres',
      'Healthy coral formations and volcanic rock structures',
      'Frequent encounters with large pelagic species',
      'Multiple dive sites suitable for varying experience levels',
    ],
    visibility: '25m - 40m',
    waterTemp: '24°C - 28°C (75°F - 82°F)',
    bestSeason: 'October to April',
    weatherConditions: 'Moderate to strong currents, suitable for advanced divers.',
    image: diveSafariImages.coinDeMire,
  },
  {
    id: 'ile-plate',
    name: 'Ile Plate',
    tagline: 'Explore the Waters of Ile Plate',
    description: 'Located north of Mauritius, Ile Plate is one of the most remote and rewarding diving destinations in the region. Surrounded by pristine reefs and crystal-clear waters, the island offers exceptional diving opportunities for those seeking adventure beyond the mainland.',
    location: 'Northern Mauritius',
    maxDepth: '35m (115ft)',
    certificationLevel: 'Intermediate',
    type: ['Reef', 'Deep'],
    marineLife: ['Clownfish', 'Parrotfish', 'Moray Eels', 'Trevally'],
    highlights: [
      'Remote and unspoiled dive sites',
      'Excellent underwater visibility',
      'Diverse coral reef ecosystems',
      'Abundant marine life',
      'Unique volcanic and reef formations',
    ],
    visibility: '20m - 35m',
    waterTemp: '25°C - 27°C (77°F - 81°F)',
    bestSeason: 'Year-round (Best: May to September)',
    weatherConditions: 'Generally calm with light to moderate currents.',
    image: diveSafariImages.ilePlate,
  },
  {
    id: 'round-island',
    name: 'Round Island',
    tagline: 'Shark Diving at Round Island',
    description: 'Located northeast of Mauritius, Round Island is one of the country\'s most exciting advanced dive destinations. Its remote location, strong currents, and deep waters attract larger pelagic species, making it a prime site for shark encounters.',
    location: 'Northeast Mauritius',
    maxDepth: '30m (100ft)',
    certificationLevel: 'Advanced',
    type: ['Reef', 'Deep', 'Drift', 'Wall'],
    marineLife: ['Grey Reef Sharks', 'Whitetip Reef Sharks', 'Silvertip Sharks', 'Hammerhead Sharks'],
    highlights: [
      'One of Mauritius\' top locations for pelagic marine life',
      'Dramatic underwater walls and volcanic formations',
      'Clear blue-water conditions',
      'Remote and uncrowded dive sites',
      'Excellent opportunities for advanced divers',
    ],
    visibility: '20m - 30m',
    waterTemp: '26°C - 28°C (79°F - 82°F)',
    bestSeason: 'Year-round',
    weatherConditions: 'Strong currents, remote location. Recommended for advanced divers.',
    image: diveSafariImages.roundIsland,
  },
  {
    id: 'passe-st-jacques',
    name: 'Passe St-Jacques',
    description: 'Located in Southern Mauritius, Passe St-Jacques is a world-class dive site featuring dramatic underwater canyons, strong currents, and encounters with large pelagic species. A favorite among technical divers.',
    location: 'Southern Mauritius',
    maxDepth: '45m (150ft)',
    certificationLevel: 'Advanced',
    type: ['Deep', 'Drift', 'Wall'],
    marineLife: ['Hammerhead Sharks', 'Eagle Rays', 'Jacks', 'Tuna'],
    visibility: '25m - 40m',
    waterTemp: '23°C - 26°C (73°F - 79°F)',
    bestSeason: 'May to September',
    weatherConditions: 'Strong currents, requires advanced skills and experience.',
    image: diveSafariImages.passeStJacques,
  },
];
